### ISSUE TITLE
Issues with tests

### ISSUE THREAD

**Issue by hprovenza** [rqlite/rqlite-java#4]
I'm having trouble with the tests, which are failing out-of-the-box.

1) I need to establish an rqlite server separately before I run the tests, which is not noted in documentation.  I had expected them to work standalone.
2) After the first test, subsequent testing runs fail because the first two tests in RqliteClientTest do not clean up the data that they've inserted.  I've fixed this by dropping tables foo and bar at the end of the test and I'll submit a PR after I've resolved the next point
3) testCreateRqliteInstancePing(com.rqlite.RqliteFactoryTest): expected:<[unknown]> but was:<[v5.4.0]>.  Is installing rqlite supposed to set an $RQLITE_VERSION environment variable or do I have to do it manually?  My server is up and running but this variable is not set.

Thanks!

**Comment by hprovenza** [comment]
As an update, I see from searching through the other repos that RQLITE_VERSION is set in the docker release. Can I remove this test, since the tests shouldn't depend on using rqlite through docker?

**Comment by hprovenza** [comment]
As an update, I see from searching through the other repos that RQLITE_VERSION is set in rqlite-docker.  Is rqlite-java only meant to be run with rqlite-docker?

**Comment by hprovenza** [comment]
As an update, I see from searching through the other repos that RQLITE_VERSION is set in rqlite-docker.  Is rqlite-java only meant to be run with rqlite-docker?

**Comment by hprovenza** [comment]
As an update, I see from searching through the other repos that RQLITE_VERSION is set in rqlite-docker.  Is rqlite-java only meant to be run with rqlite-docker?

**Comment by hprovenza** [comment]
As an update, I see from searching through the other repos that RQLITE_VERSION is set in rqlite-docker.  Is rqlite-java only meant to be run with rqlite-docker?

**Comment by hprovenza** [comment]
As an update, I see from searching through the other repos that RQLITE_VERSION is set in rqlite-docker.  Is rqlite-java only meant to be run with rqlite-docker?

**Comment by otoolep** [comment]
Thanks for your report. The code is this repo is rather old, I'm not surprised you hit some rough spots.

No, this client is meant to run with any rqlite node, it's just that I test it with a Docker instance. That's why it doesn't do any cleanup, since the container just go aways at the end of testing (in CircleCI).
